### ISSUE TITLE
unsubscriber for onAuthStateChanged

### ISSUE THREAD

**Issue by vinaydate** [gojutin/easy-peasy-todos#1]
Thanks a lot for this repo. Was trying to figure out how firebase snapshot listeners be included in easy-peasy architecture.

One suggestion: May be we are missing on one memory leak.

`auth().onAuthStateChanged`

We should have another unregister action for this also.

**Comment by just214** [comment]
Hey @vinaydate, I'm sorry for the delayed response! I just happened to see this today while going through my old repos. I actually thought about that as well, but didn't think it was necessary since you want that socket open at all times during the browsing session. But, I guess it's not a good idea to count on the browser closing your connections for you. I will go ahead and update that as well as update all the dependencies.

**Comment by just214** [comment]
Just realized that there are quite a few breaking changes in v2 of easy-peasy, so it might take a little longer than I thought. I might also write an alternative TypeScript implementation as well.

**Comment by vinaydate** [comment]
Moved on to different platform
